# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Morris
email: morrisj68@gmail.com
description: > 
  The Personal Website for John Morris.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://johnmichaelmorris.com" # the base hostname & protocol for your site
github_username:  jmojmojmo
version-number: 0.1
markdown: kramdown
permalink: /:title # to style URLs like /the-name-of-the-art.html